### PR TITLE
Backend endpoints

### LINKED ISSUE #45: Backend Endpoints
Backend endpoints that accept POST and GET requests to control drones, accept orders, etc...
This does NOT include push notifications to employees/clients. Push messaging is more complex and requires client subscription to either the backend or a third party service.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Drone and Credit API not up yet, and thus cannot implement backend endpoints for them.

**Review by mdunaevs — CHANGES_REQUESTED** [review]
There are now merge conflicts can you fix them?

**Comment by ghost** [comment]
> There are now merge conflicts can you fix them?

Resolved.

**Review by mdunaevs — APPROVED** [review]
Looks goof now thanks

**Pull request merged**
